# Generated by Django 2.2 on 2019-06-21 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('confirmpassword', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('img', models.URLField(max_length=500)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=150)),
                ('websitename', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('BOOK', 'BOOK'), ('VIDEO', 'VIDEO')], default='VIDEO', max_length=150)),
                ('plan', models.CharField(choices=[('FREE', 'FREE'), ('PAID', 'PAID')], default='FREE', max_length=150)),
                ('audience', models.CharField(choices=[('BEGINNER', 'BEGINNER'), ('ADVANCED', 'ADVANCED')], default='BEGINNER', max_length=150)),
                ('tech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Technology')),
            ],
        ),
    ]
