# Generated by Django 2.2 on 2019-06-22 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_tutorial_upvote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
